version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    env_file: .env
    restart: always

  frontend:
    build: ./EV-Charging-web
    ports:
      - "3000:80"
    restart: always
